### ISSUE TITLE
location for .txt-files

### ISSUE THREAD

**Issue by ImkeF** [fluf1024/PQGoogleSpreadsheet#1]
Thanks for this awesome connector! 
Managed to make it work if I replaced the reference to the client_id.txt and client_secret.txt by hardcoded values, but would prefer to handle them as variables instead. Where am I supposed to put the files in order to make this work?

**Comment by fluf1024** [comment]
Hi @ImkeF, .mez file is just an ZIP file. You can rename it to .mez.zip and add thoose two files to archive withnout installing or running Visual Studio and then rename it to .mez again. I have updated the connector and I'm working on tutorial. Would be ok for you if I quote your web article?

**Comment by ImkeF** [comment]
Hi Honza,

Thank you!

And yes, please quote my article.

Thanks again for your awesome code – cheers, Imke
